// <auto-generated />
using ForTrek.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ForTrek.API.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("ForTrek.API.Models.Marca", b =>
                {
                    b.Property<int>("MarcaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ano_fundacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("CEO")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fundador")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sede")
                        .HasColumnType("TEXT");

                    b.Property<string>("site")
                        .HasColumnType("TEXT");

                    b.HasKey("MarcaId");

                    b.ToTable("marcas");
                });
#pragma warning restore 612, 618
        }
    }
}
